name:                Story-Teller-Engine
version:             0.1.1.0
github:              "progala2/Story-Teller-Engine"
license:             MIT
author:              "Przemysław Rogala"
maintainer:          "progala2@o2.pl"
copyright:           "2019 Przemysław Rogala"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/progala2/Story-Teller-Engine/blob/master/README.md>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers

library:
  source-dirs: src

executables:
  Story-Teller-Engine-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Story-Teller-Engine

tests:
  Story-Teller-Engine-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Story-Teller-Engine
